version: "3.9"

services:
  api:
    image: $DOCKER_USER/$REPO_NAME:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    restart: always
    ports:
      - "4000:4000"
#    healthcheck:
#      test: curl -s$ http://158.160.37.55:4000/ping/ || exit 1
#      interval: 15s
#      timeout: 5s
#      retries: 5