name: Build and deploy workflow
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: docker build
        env:
          HOME: ./
        run: docker build -t ${{ secrets.DOCKER_USER }}/${{ secrets.REPO_NAME }}:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      - name: docker push
        run: docker push ${{ secrets.DOCKER_USER }}/${{ secrets.REPO_NAME }}:$GITHUB_REF_NAME-$GITHUB_RUN_ID

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: print the latest image tag
        run: echo The latest image tag is $GITHUB_REF_NAME-$GITHUB_RUN_ID
      - name: deploy app
        uses: appleboy/ssh-action@master
        env:
          GITHUB_REF_NAME: $GITHUB_REF_NAME
          GITHUB_RUN_ID: $GITHUB_RUN_ID
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          envs: GITHUB_REF_NAME, GITHUB_RUN_ID
          script: |
            docker rm -f ${{ secrets.REPO_NAME }}
            docker run --name ${{ secrets.REPO_NAME }} -p 4000:4000/tcp -it -d ${{ secrets.DOCKER_USER }}/${{ secrets.REPO_NAME }}:$GITHUB_REF_NAME-$GITHUB_RUN_ID
            docker image prune -a -f
