name: Build and deploy workwlow
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: docker build
        env:
          HOME: ./
        run: docker build -t ${{ secrets.DOCKER_USER }}/${{ secrets.REPO_NAME }}:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      - name: docker push
        run: docker push ${{ secrets.DOCKER_USER }}/${{ secrets.REPO_NAME }}:$GITHUB_REF_NAME-$GITHUB_RUN_ID

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: clone code
        uses: actions/checkout@v2
#      - name: secrets-to-env-action
#        uses: oNaiPs/secrets-to-env-action@v1
#        with:
#          secrets: ${{ toJSON(secrets) }}
#          convert: lower
#      - run: echo "Value of DOCKER_USER $DOCKER_USER"
#      - name: render config
#        run:  cat docker-compose-ci.yaml | envsubst '$DOCKER_USER, $REPO_NAME, $GITHUB_REF_NAME, $GITHUB_RUN_ID' > deploy/docker-compose.yaml
#      - name: copy files to server
#        uses: appleboy/scp-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          key: ${{ secrets.KEY }}
#          source: "deploy/*"
#          target: "Insta-light"
#          strip_components: 1
      - name: deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd Insta-light
            docker system prune -f
            docker run --name ${{ secrets.REPO_NAME }} -p 158.160.37.55:4000:4000/tcp -it -d ${{ secrets.DOCKER_USER }}/${{ secrets.REPO_NAME }}:$GITHUB_REF_NAME-$GITHUB_RUN_ID
